// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imsguyidxtmusvghenxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imltc2d1eWlkeHRtdXN2Z2hlbnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4MTM1NjQsImV4cCI6MjA4MTM4OTU2NH0.SwJHSkHOIbMyAJIMZBKSPAbd59VriUEjm2Tys4fOBpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});