// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://pqnmgstlxmfkrnjyehkk.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxbm1nc3RseG1ma3JuanllaGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3Njc0NzEsImV4cCI6MjA4MDM0MzQ3MX0.55EfKeygCMwA9tQANFiHX0Kdl_EyzTEo98vMDV72amM';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});